spring.application.name=booky
server.port=${PORT:8080}
spring.datasource.url=${BOOKY_DB_URL}
spring.datasource.username=${BOOKY_DB_USERNAME}
spring.datasource.password=${BOOKY_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${BOOKY_SHOW_SQL:false}
spring.jpa.properties.hibernate.format_sql=${BOOKY_FORMAT_SQL:false}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${BOOKY_MAIL_USERNAME:disabled@booky.local}
spring.mail.password=${BOOKY_MAIL_PASSWORD:disabled}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

booky.email.enabled=false